app/main/routes.py
from flask import render_template, Blueprint
from flask_login import login_required

bp = Blueprint('main', __name__, template_folder='templates')


@bp.route('/')
@bp.route('/index')
def index():
    return render_template('index.html', title='Home', main_page=True)
    
@bp.route('/mentions')
def mentions():
    return render_template('mentions.html', title='Mentions Légales', main_page=False)

@bp.route('/billetterie')
@login_required
def billetterie():
    return render_template("billetterie.html", title="Billeterie")
    

app/templates/_base2.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="static/css/theme.css">

  {% block title %} 
  {% if title %}
  <title>{{ title }} - Gala Sigma</title>
  {% else %}
  <title>Gala Sigma</title>
  {% endif %} 
  {% endblock %}
</head>

<body>

  <!-- navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="">
    <div class="container"> <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse" data-target="#navbar11">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar11">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item text-light"> <a class="nav-link text-light" href="{{ url_for('main.index') }}">Home</a> </li>
          {% if main_page %}
          <li class="nav-item text-light"> <a class="nav-link text-light" href="#about">A propos</a> </li>
          <li class="nav-item"> <a class="nav-link text-light" href="#planning">Planning</a> </li>
          <li class="nav-item"> <a class="nav-link text-light" href="#team">L'Equipe</a> </li>
          {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if main_page %}
          <li class="nav-item"> <a class="nav-link text-light" href="#tarifs">Les Tarifs</a> </li>
          <li class="nav-item"> <a class="nav-link text-light" href="#tutos">Tutos</a> </li>
          <li class="nav-item"> <a class="nav-link text-light" href="#partenaires">Nos Partenaires</a> </li>
          {% endif %}
        </ul> 
        {% if current_user.is_anonymous %}
        <a class="btn btn-primary navbar-btn ml-md-2 text-light">Register</a>
        {% endif %}
      </ul>
      </div>
    </div>
  </nav>


  <!-- Flash messages -->
  {% with messages = get_flashed_messages() %} 
  {% if messages %}
  <div class="bg-primary inset-shadowed">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-sm-12">
          {% for message in messages %}
          <div class="alert alert-dark" style="margin-top: 5em;" role="alert">
            <p class="mb-0">{{ message}}</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% endfor %} 
  {% endif %} 
  {% endwith %}

  {% block app_content %}
  {% endblock %} 

    
  <!-- Footer -->
  <div class="bg-dark text-light">
    <div class="container">
      <div class="row">
        <div class="p-4 col-md-6">
          <h2 class="mb-4">Gala Sigma</h2>
          <ul class="list-unstyled"> <a href="#" class="text-light">Home</a> <br> <a href="#" class="text-light">About us</a> <br> <a href="#" class="text-light">Our services</a> <br> <a href="#" class="text-light">Stories</a> </ul>
        </div>
        <div class="p-4 col-md-6">
          <h2 class="mb-4">Contact</h2>
          <p> <a href="#" class="text-light">
              <i class="fa d-inline mr-3 text-muted fa-phone"></i>0</a>686491495 : Respo SLC /&nbsp;<br></p>
          <p> <a href="#" class="text-light">
              <i class="fa d-inline mr-3 text-muted fa-envelope-o"></i>info@pingendo.com</a> </p>
          <p> <a href="#" class="text-light">
              <i class="fa d-inline mr-3 fa-map-marker text-muted"></i>2</a>3 rue Roches Genes</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 mt-3">
          <p class="text-center">© Copyright 2018 Gala Sigma Clermont - All rights reserved. </p>
        </div>
      </div>
    </div>
  </div>
  <script src="static/js/jquery-3.2.1.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="static/js/bootstrap.min.js"></script>
</body>

</html>

app/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>{{ field.label }}
    <dd>{{ field(**kwargs)|safe }} {% if field.errors %}
        <ul class=errors>
            {% for error in field.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </dd>
{% endmacro %}

app/templates/placement.html
{% extends "_base.html" %} 

{% block app_content %}
<h1>Hi, {{ current_user.email }}!</h1>
<p>
    <br />Bienvenue sur le site de la Remise Des Diplômes de SIGMA Clermont 2017, école née de la fusion entre l’ENSCCF et de l’IFMA.
    <br />
    <br /> Fin 2017, la première promo 100% SIGMA est passée, et après un an de fusion complète, nous nous apprêtons à fêter la
    deuxième remise des diplômes de notre nouvelle école. La cérémonie aura lieu le
    <em>samedi 7 Octobre</em> au
    <em>Polydôme</em> de Clermont-Ferrand.
    <br />
    <br/> Cette année, 275 diplomés recevront leur diplôme d'ingénieur.
    <br />
    <br/> Une cérémonie de prestige sera menée par M. Frédéric Briand, directeur du site SANOFI de Vertolaye et parrain de la
    promotion 2017. Ensuite, un cocktail puis un dîner et une soirée de gala, permettront aux nouveaux ingénieurs de fêter
    leur entrée dans la vie active avec panache.
    <br />
    <br/> Avec un programme d’enseignement défini en partenariat avec la Fondation SIGMA et ses entreprises fondatrices ou associées,
    l’école forme des ingénieurs d’un haut niveau scientifique et technique, conscients de leurs responsabilités vis-à-vis
    de la société, des ingénieurs capables de s’adapter et de développer une expertise technique sur des projets à dimension
    internationale, des ingénieurs où le savoir être complète harmonieusement le savoir et le savoir-faire.
</p>
{% endblock %}

app/templates/wtf.html
{% macro form_errors(form, hiddens=True) %}
  {%- if form.errors %}
    {%- for fieldname, errors in form.errors.items() %}
      {%- if bootstrap_is_hidden_field(form[fieldname]) and hiddens or
             not bootstrap_is_hidden_field(form[fieldname]) and hiddens != 'only' %}
        {%- for error in errors %}
          <p class="error">{{error}}</p>
        {%- endfor %}
      {%- endif %}
    {%- endfor %}
  {%- endif %}
{%- endmacro %}

{% macro _hz_form_wrap(horizontal_columns, form_type, add_group=False, required=False) %}
{% if form_type == "horizontal" %}
  {% if add_group %}<div class="form-group{% if required %} required{% endif %}">{% endif %}
  <div class="col-{{horizontal_columns[0]}}-offset-{{horizontal_columns[1]}}
              col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}
             ">
{% endif %}
{{caller()}}

{% if form_type == "horizontal" %}
  {% if add_group %}</div>{% endif %}
  </div>
{% endif %}
{% endmacro %}

{% macro form_field(field,
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    button_map={}) %}

{# this is a workaround hack for the more straightforward-code of just passing required=required parameter. older versions of wtforms do not have
the necessary fix for required=False attributes, but will also not set the required flag in the first place. we skirt the issue using the code below #}
{% if field.flags.required and not required in kwargs %}
{% set kwargs = dict(required=True, **kwargs) %}
{% endif %}

{% if field.widget.input_type == 'checkbox' %}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    <div class="checkbox">
      <label>
        {{field()|safe}} {{field.label.text|safe}}
      </label>
    </div>
  {% endcall %}
{%- elif field.type == 'RadioField' -%}
  {# note: A cleaner solution would be rendering depending on the widget,
     this is just a hack for now, until I can think of something better #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    {% for item in field -%}
      <div class="radio">
        <label>
          {{item|safe}} {{item.label.text|safe}}
        </label>
      </div>
    {% endfor %}
  {% endcall %}
{%- elif field.type == 'SubmitField' -%}
  {# deal with jinja scoping issues? #}
  {% set field_kwargs = kwargs %}

  {# note: same issue as above - should check widget, not field type #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    {{field(class='btn btn-%s' % button_map.get(field.name, 'default'),
            **field_kwargs)}}
  {% endcall %}
{%- elif field.type == 'FormField' -%}
{# note: FormFields are tricky to get right and complex setups requiring
   these are probably beyond the scope of what this macro tries to do.
   the code below ensures that things don't break horribly if we run into
   one, but does not try too hard to get things pretty. #}
  <fieldset>
    <legend>{{field.label}}</legend>
    {%- for subfield in field %}
      {% if not bootstrap_is_hidden_field(subfield) -%}
        {{ form_field(subfield,
                      form_type=form_type,
                      horizontal_columns=horizontal_columns,
                      button_map=button_map) }}
      {%- endif %}
    {%- endfor %}
  </fieldset>
{% else -%}
  <div class="form-group {% if field.errors %} has-error{% endif -%}
                         {%- if field.flags.required %} required{% endif -%}
  ">
      {%- if form_type == "inline" %}
        {{field.label(class="sr-only")|safe}}
        {% if field.type == 'FileField' %}
          {{field(**kwargs)|safe}}
        {% else %}
          {{field(class="form-control", **kwargs)|safe}}
        {% endif %}
      {% elif form_type == "horizontal" %}
        {{field.label(class="control-label " + (
          " col-%s-%s" % horizontal_columns[0:2]
        ))|safe}}
        <div class=" col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}">
          {% if field.type == 'FileField' %}
            {{field(**kwargs)|safe}}
          {% else %}
            {{field(class="form-control", **kwargs)|safe}}
          {% endif %}
        </div>
        {%- if field.errors %}
          {%- for error in field.errors %}
            {% call _hz_form_wrap(horizontal_columns, form_type, required=required) %}
              <p class="help-block">{{error}}</p>
            {% endcall %}
          {%- endfor %}
        {%- elif field.description -%}
          {% call _hz_form_wrap(horizontal_columns, form_type, required=required) %}
            <p class="help-block">{{field.description|safe}}</p>
          {% endcall %}
        {%- endif %}
      {%- else -%}
        {{field.label(class="control-label")|safe}}
        {% if field.type == 'FileField' %}
          {{field(**kwargs)|safe}}
        {% else %}
          {{field(class="form-control", **kwargs)|safe}}
        {% endif %}

        {%- if field.errors %}
          {%- for error in field.errors %}
            <p class="help-block">{{error}}</p>
          {%- endfor %}
        {%- elif field.description -%}
          <p class="help-block">{{field.description|safe}}</p>
        {%- endif %}
      {%- endif %}
  </div>
{% endif %}
{% endmacro %}

{# valid form types are "basic", "inline" and "horizontal" #}
{% macro quick_form(form,
                    action="",
                    method="post",
                    extra_classes=None,
                    role="form",
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    enctype=None,
                    button_map={},
                    id="",
                    novalidate=False,
                    render_kw={}) %}
{#-
action="" is what we want, from http://www.ietf.org/rfc/rfc2396.txt:

4.2. Same-document References

   A URI reference that does not contain a URI is a reference to the
   current document.  In other words, an empty URI reference within a
   document is interpreted as a reference to the start of that document,
   and a reference containing only a fragment identifier is a reference
   to the identified fragment of that document.  Traversal of such a
   reference should not result in an additional retrieval action.
   However, if the URI reference occurs in a context that is always
   intended to result in a new request, as in the case of HTML's FORM
   element, then an empty URI reference represents the base URI of the
   current document and should be replaced by that URI when transformed
   into a request.

 -#}
{#- if any file fields are inside the form and enctype is automatic, adjust
    if file fields are found. could really use the equalto test of jinja2
    here, but latter is not available until 2.8

    warning: the code below is guaranteed to make you cry =(
#}
{%- set _enctype = [] %}
{%- if enctype is none -%}
  {%- for field in form %}
    {%- if field.type == 'FileField' %}
      {#- for loops come with a fairly watertight scope, so this list-hack is
          used to be able to set values outside of it #}
      {%- set _ = _enctype.append('multipart/form-data') -%}
    {%- endif %}
  {%- endfor %}
{%- else %}
  {% set _ = _enctype.append(enctype) %}
{%- endif %}
<form
  {%- if action != None %} action="{{action}}"{% endif -%}
  {%- if id %} id="{{id}}"{% endif -%}
  {%- if method %} method="{{method}}"{% endif %}
  class="form
    {%- if extra_classes %} {{extra_classes}}{% endif -%}
    {%- if form_type == "horizontal" %} form-horizontal
    {%- elif form_type == "inline" %} form-inline
    {%- endif -%}
  "
  {%- if _enctype[0] %} enctype="{{_enctype[0]}}"{% endif -%}
  {%- if role %} role="{{role}}"{% endif -%}
  {%- if novalidate %} novalidate{% endif -%}
  {%- if render_kw %} {{render_kw|xmlattr}}{% endif -%}
  >
  {{ form.hidden_tag() }}
  {{ form_errors(form, hiddens='only') }}

  {%- for field in form %}
    {% if not bootstrap_is_hidden_field(field) -%}
      {{ form_field(field,
                    form_type=form_type,
                    horizontal_columns=horizontal_columns,
                    button_map=button_map) }}
    {%- endif %}
  {%- endfor %}

</form>
{%- endmacro %}